### ISSUE TITLE
Getting error 400 client version 1.12 is too old. Minimum supported API version is 1.24, please upgrade your client to a newer version

### ISSUE THREAD

**Issue by wesrl** [Xantios/cockpit-docker#28]
I updated my Ubuntu server and I guess Docker might have decided to move on with a new API version. I was mainly wondering if anyone has found a work around besides switching to Podman and going with cockpit-podman.
Error - 400 client version 1.12 is too old. Minimum supported API version is 1.24, please upgrade your client to a newer version
Ubuntu 22.04.3 LTS 
Docker version is 25.0.3, build 4debf4, 
Docker compose is v2.24.5
![image](https://github.com/Xantios/cockpit-docker/assets/94072147/0e6a6a7d-2b40-4827-9d35-f45de96cca44)

**Comment by Bortus-AI** [comment]
same here

**Comment by acsimmonds** [comment]
Yep, same.  Guessing this is something coded into the plugin as all of my containers are using a higher version (which is what other web searches say is the fix)

**Comment by acsimmonds** [comment]
Ok, I'm not sure this is the right way to do things, but I did fix it.  Here's how:

Open /usr/share/cockpit/docker/docker.js however you can to be able to edit it (I made a backup and edited that)

Replace every instance of "v1.12" with "v1.24"

Log out of cockpit and back in.

**Comment by wesrl** [comment]
> Ok, I'm not sure this is the right way to do things, but I did fix it. Here's how:
> 
> Open /usr/share/cockpit/docker/docker.js however you can to be able to edit it (I made a backup and edited that)
> 
> Replace every instance of "v1.12" with "v1.24"
> 
> Log out of cockpit and back in.

Ok I will try that out. Sounds promising

**Comment by mikecel79** [comment]
> Ok, I'm not sure this is the right way to do things, but I did fix it. Here's how:
> 
> Open /usr/share/cockpit/docker/docker.js however you can to be able to edit it (I made a backup and edited that)
> 
> Replace every instance of "v1.12" with "v1.24"
> 
> Log out of cockpit and back in.

Tried this today and it worked for me.  Thanks!

**Comment by wesrl** [comment]
> Ok, I'm not sure this is the right way to do things, but I did fix it. Here's how:
> 
> Open /usr/share/cockpit/docker/docker.js however you can to be able to edit it (I made a backup and edited that)
> 
> Replace every instance of "v1.12" with "v1.24"
> 
> Log out of cockpit and back in.

Worked great thanks.

**Comment by Ic3Nine** [comment]
Chime in with - this worked for me too.

Do you all see cpu and memory usage for the containers?  mine are blank.
![image](https://github.com/Xantios/cockpit-docker/assets/11322798/0467c528-8408-4000-8033-72c1aa9ebd58)
![image](https://github.com/Xantios/cockpit-docker/assets/11322798/7df480cb-6953-4531-8ec2-276d649e7550)
