### ISSUE TITLE
Not running

### ISSUE THREAD

**Issue by ezraholm50** [Xantios/cockpit-docker#4]
Hello,

Thanks for taking the time to fork this cool feature. 
When i install it and click on docker (fork) top right shows "oops" in red, thats it. Logs output nothing. 
Could you advise what/where to check?

Thanks again!

![DeepinScreenshot_select-area_20210216222249](https://user-images.githubusercontent.com/13510720/108123044-89475400-70a5-11eb-9001-ac5a5ba65fa5.png)
![DeepinScreenshot_select-area_20210216222420](https://user-images.githubusercontent.com/13510720/108123173-bdbb1000-70a5-11eb-8da8-9e5bb8bea1f5.png)
![DeepinScreenshot_select-area_20210216222410](https://user-images.githubusercontent.com/13510720/108123176-beec3d00-70a5-11eb-9f9b-2a6cf88a2cf4.png)

**Comment by Xantios** [comment]
Hey,

This mostly looks like a connection issue. 
you seem to be connecting over a VPN, check the port mapping and try to connect directly to it :-)

**Comment by ezraholm50** [comment]
Nope, connecting locally. Theres no port mapping to be checked. Connecting to https://ip:9090 on debian.

Please advise.

**Comment by Xantios** [comment]
The error you are receiving is not from the plugin itself, so start with the usual test steps.

- Connect using a other browser (i myself use Firefox, Brave and Safari on MacOS )
- Disable extensions (the log show you have some element blocker and a VPN thing installed, hence my question)
- try connecting with as little as possible hardware between the server and the browser you are using (no firewalls, no extra routers etc)

I can not reproduce this bug, and the file throwing this issue (background.js) is not in this plugin. please check (considering you are running Debian) that you have a compatible version of Cockpit running :-)
