### ISSUE TITLE
Docker page not scrollable?

### ISSUE THREAD

**Issue by uberduck** [Xantios/cockpit-docker#5]
I have noticed that the docker page is not scrollable - as in there are contents extending beyond the screen, but the page does not offer any abilities to scroll, I can't even select text and drag it down the page to make it move. 

Is this affecting anyone else?

**Comment by Xantios** [comment]
hey,

I never heard of such problems, are you sure you are using one of the supported browsers?

**Comment by Xantios** [comment]
@uberduck tried it on a screen the size of a post-stamp (2009 MBP) scrolls like a charm in all browsers i tested it with.

What are you using (OS and Browser)

**Comment by uberduck** [comment]
Sorry for the late response @Xantios. 
I have tried this across multiple OSes and browsers, including Chrome and Edge on my Windows 10 machine, and Chrome on my work mac, and even Chrome on my Android phone. 

I have also tried to rebuild cockpit-docker using the new ./install script, no difference. 

Is there anything I can do with the developer console to see what's preventing the page from scrolling?

**Comment by uberduck** [comment]
I noticed the following console error when loading up the docker page in docker, not sure if it bares any weight? 

```
Refused to apply inline style because it violates the following Content Security Policy directive: "default-src 'self' https://hostname:9090". Either the 'unsafe-inline' keyword, a hash ('sha256-473EQpjcHBSa+/TImW+5JCeuQeRkm5NapJWZ43hSuFU='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.
```

**Comment by uberduck** [comment]
I think my version of cockpit on Stream 8 is just too far ahead. 
I had encountered some issues with my Stream 8 and I reinstalled with Centos 8, which is on 224.2, which resolved this issue. 

I'll mark this as closed for now. Thanks for your attention!
