### ISSUE TITLE
install fails

### ISSUE THREAD

**Issue by echtelerp** [Xantios/cockpit-docker#6]
cockpit/cockpit-docker $ sudo ./install 
Sending build context to Docker daemon  1.805MB
Step 1/4 : FROM node:12-alpine
12-alpine: Pulling from library/node
1a3a062e2a46: Already exists 
5c011617ab43: Already exists 
eb78b7190c82: Already exists 
7c9d06233a93: Already exists 
Digest: sha256:5d8b181a0738654bbe659a68879298f8d2d4256685282ee1c2330d97c33e3eee
Status: Downloaded newer image for node:12-alpine
 ---> 4fa66bcc90de
Step 2/4 : WORKDIR /app
 ---> Running in 8cd71e9e1fe4
Removing intermediate container 8cd71e9e1fe4
 ---> cd0a7a8c6fad
Step 3/4 : RUN apk update ; apk add git
 ---> Running in 0a857d9af763
failed to create endpoint suspicious_lumiere on network bridge: failed to add the host (vethd308777) <=> sandbox (vethc15c1cc) pair interfaces: operation not supported
Error: No such container: cockpit-docker
Unable to find image 'cockpit-docker:latest' locally
docker: Error response from daemon: pull access denied for cockpit-docker, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
===> List of packages, if all went fine this list should container docker
apps                 Applications                             /usr/share/cockpit/apps
base1                                                         /usr/share/cockpit/base1
metrics                                                       /usr/share/cockpit/metrics
network              Networking                               /usr/share/cockpit/networkmanager
pcp                                                           /usr/share/cockpit/pcp
performance                                                   /usr/share/cockpit/tuned
shell                                                         /usr/share/cockpit/shell
ssh                                                           /usr/share/cockpit/ssh
static                                                        /usr/share/cockpit/static
storage              Storage                                  /usr/share/cockpit/storaged
system               Services, Overview, Logs, Terminal       /usr/share/cockpit/systemd
updates              Software Updates                         /usr/share/cockpit/packagekit
users                Accounts                                 /usr/share/cockpit/users
checksum = 414b50723feb785395b413f5a125ab9e5db2bf9b3b4b1f26099ecfc0583c840e

**Comment by Xantios** [comment]
Hi,

First things first, this is a side project and is all done from the goodness of me and those who are contributing in any way shape or form. just copy/pasting an error without any question or expectation is just rude. 

second you are running docker as root. please read the docker documentation on how docker can and should be run as a user (add yourself to the docker group)

third the issue you are facing is a docker issue not related to this package.

If you need any further assistance please bare above in mind and create a new issue
